version: '3.8'

services:
  db:
    image: postgres:15
    container_name: webrise-db
    environment:
      POSTGRES_DB: webrise
      POSTGRES_USER: webrise
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - webrise-net

  app:
    build: .
    container_name: webrise-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/webrise
      SPRING_DATASOURCE_USERNAME: webrise
      SPRING_DATASOURCE_PASSWORD: secret
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8081
    networks:
      - webrise-net

volumes:
  db_data:

networks:
  webrise-net: